### ISSUE TITLE
make the GA key optional

### ISSUE THREAD

**Issue by crahal** [OxfordDemSci/gwasdiversitymonitor#2]
make the GA key optional in config.py

**Comment by ianknowles** [comment]
after debugging the injection of GA scripts does not work behind the cloudfront cache. the cookie is set correctly but cloudfront continues to serve its cached html version of the page. Adjusted the cache key to use the `cookie_consent` cookie. This allows cloudfront to cache versions of pages with and without the GA scripts injected as the cookie only has a true/false value. Adding it to the origin requests instead of the cache key would prevent caching of all the html pages (necessary when the value is not limited to a handful of options).
